# --- !Ups

CREATE TABLE IF NOT EXISTS "user" (
    user_id INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
    password VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
) DEFAULT CHARACTER SET ascii COLLATE ascii_bin';

# --- !Downs

DROP TABLE "user" IF EXISTS;

